---
- hosts: localhost
  gather_facts: false

  tasks: 
    - name: "Learning the debug module"
      debug:
        msg: "Debug module allows us to print to the screen --> {{ item }}"
      with_items:
      - "1) A hyphen represnts an item on a list"
      - "2) So the second item on the list is this"
      - "3) Where this would be the third"
      - "4) item var is always replaced by an item from the with_items list"

