---
- name: Another network playbook example
  # The line below calls our group that does not have any clear-text passwords
  hosts: aristaswitchessecure
  # gather_facts ALWAYS runs set.py (server module)
  gather_facts: no #v2.5=< no is deault if network_cli is selected for connection
                # if turned to yes you'll collect info about the local host
  
  # Instead we will store our encrypted information within a YAML file, vault.yml
  vars_files:
    - vault.yml

  tasks:
    # is we run this and have gather_facts set to no, then ansible_facts will be about our network devs
    - name: Harvest Arista Facts
      eos_facts:
      when: ansible_network_os == 'eos'


